-- Nerosa Elite Business Suite
-- Safe to run in the Supabase SQL editor. All application tables use the pos_ prefix.

create schema if not exists private;

create table if not exists public.pos_organizations (
  id bigint generated by default as identity primary key,
  name text not null default 'Nerosa Elite',
  phone text,
  address text,
  tax_number text,
  logo_url text,
  default_currency text not null default 'IQD' check (default_currency in ('IQD', 'USD')),
  exchange_rate numeric(14, 4) not null default 1310 check (exchange_rate > 0),
  invoice_size text not null default '80mm' check (invoice_size in ('80mm', 'A4')),
  invoice_header text,
  invoice_footer text not null default 'شكراً لتسوقكم معنا',
  theme_color text not null default '#d94f82',
  scale_prefix text not null default '21',
  scale_product_digits smallint not null default 5 check (scale_product_digits between 3 and 7),
  scale_weight_digits smallint not null default 5 check (scale_weight_digits between 3 and 7),
  scale_weight_decimals smallint not null default 3 check (scale_weight_decimals between 0 and 4),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.pos_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  organization_id bigint not null references public.pos_organizations(id) on delete cascade,
  full_name text not null default '',
  email text,
  role text not null default 'cashier' check (role in ('owner', 'admin', 'manager', 'cashier', 'accountant')),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists pos_profiles_organization_id_idx on public.pos_profiles(organization_id);

create or replace function private.current_pos_org_id()
returns bigint
language sql
stable
security definer
set search_path = ''
as $$
  select p.organization_id
  from public.pos_profiles p
  where p.user_id = (select auth.uid())
    and p.is_active = true
  limit 1
$$;

create or replace function private.pos_has_role(allowed_roles text[])
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.pos_profiles p
    where p.user_id = (select auth.uid())
      and p.is_active = true
      and p.role = any(allowed_roles)
  )
$$;

revoke all on function private.current_pos_org_id() from public, anon;
revoke all on function private.pos_has_role(text[]) from public, anon;
grant usage on schema private to authenticated;
grant execute on function private.current_pos_org_id() to authenticated;
grant execute on function private.pos_has_role(text[]) to authenticated;

create or replace function private.pos_touch_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.pos_products (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.pos_organizations(id) on delete cascade,
  name text not null,
  sku text,
  barcode text,
  category text not null default 'أخرى',
  unit text not null default 'قطعة',
  cost numeric(14, 3) not null default 0 check (cost >= 0),
  retail_price numeric(14, 3) not null default 0 check (retail_price >= 0),
  wholesale_price numeric(14, 3) not null default 0 check (wholesale_price >= 0),
  currency text not null default 'IQD' check (currency in ('IQD', 'USD')),
  stock numeric(14, 3) not null default 0,
  min_stock numeric(14, 3) not null default 0 check (min_stock >= 0),
  track_weight boolean not null default false,
  scale_product_code text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, barcode),
  unique (organization_id, sku),
  unique (organization_id, scale_product_code)
);
create index if not exists pos_products_org_active_idx on public.pos_products(organization_id, is_active, name);
create index if not exists pos_products_org_stock_idx on public.pos_products(organization_id, stock) where is_active = true;

create table if not exists public.pos_customers (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.pos_organizations(id) on delete cascade,
  name text not null,
  phone text,
  address text,
  opening_balance numeric(14, 3) not null default 0,
  credit_limit numeric(14, 3) not null default 0 check (credit_limit >= 0),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists pos_customers_org_name_idx on public.pos_customers(organization_id, name);
create index if not exists pos_customers_org_phone_idx on public.pos_customers(organization_id, phone) where phone is not null;

create table if not exists public.pos_suppliers (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.pos_organizations(id) on delete cascade,
  name text not null,
  phone text,
  address text,
  opening_balance numeric(14, 3) not null default 0,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists pos_suppliers_org_name_idx on public.pos_suppliers(organization_id, name);

create table if not exists public.pos_employees (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.pos_organizations(id) on delete cascade,
  name text not null,
  phone text,
  position text,
  hire_date date not null default current_date,
  salary numeric(14, 3) not null default 0 check (salary >= 0),
  currency text not null default 'IQD' check (currency in ('IQD', 'USD')),
  is_active boolean not null default true,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists pos_employees_org_active_idx on public.pos_employees(organization_id, is_active, name);

create table if not exists public.pos_attendance (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.pos_organizations(id) on delete cascade,
  employee_id bigint not null references public.pos_employees(id) on delete cascade,
  work_date date not null default current_date,
  check_in timestamptz,
  check_out timestamptz,
  status text not null default 'present' check (status in ('present', 'absent', 'leave')),
  notes text,
  created_at timestamptz not null default now(),
  unique (organization_id, employee_id, work_date)
);
create index if not exists pos_attendance_employee_date_idx on public.pos_attendance(employee_id, work_date desc);
create index if not exists pos_attendance_org_date_idx on public.pos_attendance(organization_id, work_date desc);

create table if not exists public.pos_payroll (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.pos_organizations(id) on delete cascade,
  employee_id bigint not null references public.pos_employees(id) on delete restrict,
  payroll_month date not null,
  base_salary numeric(14, 3) not null default 0,
  bonus numeric(14, 3) not null default 0,
  deduction numeric(14, 3) not null default 0,
  net_salary numeric(14, 3) generated always as (base_salary + bonus - deduction) stored,
  currency text not null default 'IQD' check (currency in ('IQD', 'USD')),
  is_paid boolean not null default false,
  paid_at timestamptz,
  notes text,
  created_at timestamptz not null default now(),
  unique (organization_id, employee_id, payroll_month)
);
create index if not exists pos_payroll_employee_month_idx on public.pos_payroll(employee_id, payroll_month desc);
create index if not exists pos_payroll_org_month_idx on public.pos_payroll(organization_id, payroll_month desc);

create table if not exists public.pos_sales (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.pos_organizations(id) on delete cascade,
  customer_id bigint references public.pos_customers(id) on delete set null,
  invoice_number text,
  sale_type text not null default 'retail' check (sale_type in ('retail', 'wholesale', 'credit', 'installment')),
  currency text not null default 'IQD' check (currency in ('IQD', 'USD')),
  exchange_rate numeric(14, 4) not null default 1 check (exchange_rate > 0),
  subtotal numeric(14, 3) not null default 0,
  discount numeric(14, 3) not null default 0 check (discount >= 0),
  total numeric(14, 3) not null default 0,
  paid numeric(14, 3) not null default 0,
  due numeric(14, 3) generated always as (greatest(total - paid, 0)) stored,
  status text not null default 'completed' check (status in ('draft', 'completed', 'cancelled', 'returned')),
  notes text,
  sold_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  unique (organization_id, invoice_number)
);
create index if not exists pos_sales_org_date_idx on public.pos_sales(organization_id, sold_at desc);
create index if not exists pos_sales_customer_date_idx on public.pos_sales(customer_id, sold_at desc) where customer_id is not null;
create index if not exists pos_sales_org_due_idx on public.pos_sales(organization_id, due) where due > 0 and status = 'completed';

create table if not exists public.pos_sale_items (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.pos_organizations(id) on delete cascade,
  sale_id bigint not null references public.pos_sales(id) on delete cascade,
  product_id bigint not null references public.pos_products(id) on delete restrict,
  product_name text not null,
  barcode text,
  quantity numeric(14, 3) not null check (quantity > 0),
  unit_price numeric(14, 3) not null check (unit_price >= 0),
  line_total numeric(14, 3) generated always as (quantity * unit_price) stored
);
create index if not exists pos_sale_items_sale_id_idx on public.pos_sale_items(sale_id);
create index if not exists pos_sale_items_product_id_idx on public.pos_sale_items(product_id);

create table if not exists public.pos_purchases (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.pos_organizations(id) on delete cascade,
  supplier_id bigint references public.pos_suppliers(id) on delete set null,
  invoice_number text,
  supplier_invoice text,
  currency text not null default 'IQD' check (currency in ('IQD', 'USD')),
  exchange_rate numeric(14, 4) not null default 1 check (exchange_rate > 0),
  subtotal numeric(14, 3) not null default 0,
  discount numeric(14, 3) not null default 0 check (discount >= 0),
  total numeric(14, 3) not null default 0,
  paid numeric(14, 3) not null default 0,
  due numeric(14, 3) generated always as (greatest(total - paid, 0)) stored,
  status text not null default 'completed' check (status in ('draft', 'completed', 'cancelled', 'returned')),
  notes text,
  purchased_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  unique (organization_id, invoice_number)
);
create index if not exists pos_purchases_org_date_idx on public.pos_purchases(organization_id, purchased_at desc);
create index if not exists pos_purchases_supplier_date_idx on public.pos_purchases(supplier_id, purchased_at desc) where supplier_id is not null;

create table if not exists public.pos_purchase_items (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.pos_organizations(id) on delete cascade,
  purchase_id bigint not null references public.pos_purchases(id) on delete cascade,
  product_id bigint not null references public.pos_products(id) on delete restrict,
  product_name text not null,
  quantity numeric(14, 3) not null check (quantity > 0),
  unit_cost numeric(14, 3) not null check (unit_cost >= 0),
  line_total numeric(14, 3) generated always as (quantity * unit_cost) stored
);
create index if not exists pos_purchase_items_purchase_id_idx on public.pos_purchase_items(purchase_id);
create index if not exists pos_purchase_items_product_id_idx on public.pos_purchase_items(product_id);

create table if not exists public.pos_installments (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.pos_organizations(id) on delete cascade,
  sale_id bigint not null references public.pos_sales(id) on delete cascade,
  customer_id bigint not null references public.pos_customers(id) on delete restrict,
  installment_number smallint not null check (installment_number > 0),
  due_date date not null,
  amount numeric(14, 3) not null check (amount > 0),
  paid_amount numeric(14, 3) not null default 0 check (paid_amount >= 0),
  paid_at timestamptz,
  status text not null default 'pending' check (status in ('pending', 'partial', 'paid', 'late')),
  notes text,
  created_at timestamptz not null default now(),
  unique (sale_id, installment_number)
);
create index if not exists pos_installments_org_due_idx on public.pos_installments(organization_id, due_date) where status in ('pending', 'partial', 'late');
create index if not exists pos_installments_customer_due_idx on public.pos_installments(customer_id, due_date);

create table if not exists public.pos_stock_movements (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.pos_organizations(id) on delete cascade,
  product_id bigint not null references public.pos_products(id) on delete restrict,
  movement_type text not null check (movement_type in ('initial', 'purchase', 'sale', 'adjustment', 'return_in', 'return_out')),
  quantity numeric(14, 3) not null,
  reference_type text,
  reference_id bigint,
  notes text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists pos_stock_movements_product_date_idx on public.pos_stock_movements(product_id, created_at desc);
create index if not exists pos_stock_movements_org_date_idx on public.pos_stock_movements(organization_id, created_at desc);

create table if not exists public.pos_expenses (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.pos_organizations(id) on delete cascade,
  category text not null,
  amount numeric(14, 3) not null check (amount > 0),
  currency text not null default 'IQD' check (currency in ('IQD', 'USD')),
  exchange_rate numeric(14, 4) not null default 1 check (exchange_rate > 0),
  occurred_on date not null default current_date,
  notes text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists pos_expenses_org_date_idx on public.pos_expenses(organization_id, occurred_on desc);

create table if not exists public.pos_vouchers (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.pos_organizations(id) on delete cascade,
  voucher_number text,
  voucher_type text not null check (voucher_type in ('receipt', 'payment', 'waiver', 'disbursement')),
  party_type text check (party_type in ('customer', 'supplier', 'employee', 'other')),
  party_id bigint,
  party_name text,
  amount numeric(14, 3) not null check (amount > 0),
  currency text not null default 'IQD' check (currency in ('IQD', 'USD')),
  exchange_rate numeric(14, 4) not null default 1 check (exchange_rate > 0),
  voucher_date date not null default current_date,
  notes text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  unique (organization_id, voucher_number)
);
create index if not exists pos_vouchers_org_date_idx on public.pos_vouchers(organization_id, voucher_date desc);
create index if not exists pos_vouchers_party_idx on public.pos_vouchers(organization_id, party_type, party_id) where party_id is not null;

create table if not exists public.pos_account_entries (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.pos_organizations(id) on delete cascade,
  party_type text not null check (party_type in ('customer', 'supplier', 'employee', 'general')),
  party_id bigint,
  entry_type text not null,
  direction text not null check (direction in ('debit', 'credit')),
  amount numeric(14, 3) not null check (amount >= 0),
  currency text not null default 'IQD' check (currency in ('IQD', 'USD')),
  reference_type text,
  reference_id bigint,
  notes text,
  entry_date date not null default current_date,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists pos_account_entries_party_date_idx on public.pos_account_entries(organization_id, party_type, party_id, entry_date desc);
create index if not exists pos_account_entries_org_date_idx on public.pos_account_entries(organization_id, entry_date desc);

create table if not exists public.pos_audit_logs (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.pos_organizations(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity_type text,
  entity_id bigint,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists pos_audit_logs_org_date_idx on public.pos_audit_logs(organization_id, created_at desc);
create index if not exists pos_audit_logs_user_date_idx on public.pos_audit_logs(user_id, created_at desc) where user_id is not null;

drop trigger if exists pos_organizations_touch on public.pos_organizations;
create trigger pos_organizations_touch before update on public.pos_organizations for each row execute function private.pos_touch_updated_at();
drop trigger if exists pos_profiles_touch on public.pos_profiles;
create trigger pos_profiles_touch before update on public.pos_profiles for each row execute function private.pos_touch_updated_at();
drop trigger if exists pos_products_touch on public.pos_products;
create trigger pos_products_touch before update on public.pos_products for each row execute function private.pos_touch_updated_at();
drop trigger if exists pos_customers_touch on public.pos_customers;
create trigger pos_customers_touch before update on public.pos_customers for each row execute function private.pos_touch_updated_at();
drop trigger if exists pos_suppliers_touch on public.pos_suppliers;
create trigger pos_suppliers_touch before update on public.pos_suppliers for each row execute function private.pos_touch_updated_at();
drop trigger if exists pos_employees_touch on public.pos_employees;
create trigger pos_employees_touch before update on public.pos_employees for each row execute function private.pos_touch_updated_at();

alter table public.pos_organizations enable row level security;
alter table public.pos_profiles enable row level security;

drop policy if exists pos_organizations_select on public.pos_organizations;
create policy pos_organizations_select on public.pos_organizations for select to authenticated
using (id = (select private.current_pos_org_id()));
drop policy if exists pos_organizations_update on public.pos_organizations;
create policy pos_organizations_update on public.pos_organizations for update to authenticated
using (id = (select private.current_pos_org_id()) and (select private.pos_has_role(array['owner','admin'])))
with check (id = (select private.current_pos_org_id()) and (select private.pos_has_role(array['owner','admin'])));

drop policy if exists pos_profiles_select on public.pos_profiles;
create policy pos_profiles_select on public.pos_profiles for select to authenticated
using (organization_id = (select private.current_pos_org_id()));
drop policy if exists pos_profiles_insert on public.pos_profiles;
create policy pos_profiles_insert on public.pos_profiles for insert to authenticated
with check (organization_id = (select private.current_pos_org_id()) and (select private.pos_has_role(array['owner','admin'])));
drop policy if exists pos_profiles_update on public.pos_profiles;
create policy pos_profiles_update on public.pos_profiles for update to authenticated
using (organization_id = (select private.current_pos_org_id()) and (select private.pos_has_role(array['owner','admin'])))
with check (organization_id = (select private.current_pos_org_id()) and (select private.pos_has_role(array['owner','admin'])));

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'pos_products','pos_customers','pos_sales','pos_sale_items','pos_installments','pos_stock_movements'
  ] loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('drop policy if exists %I on public.%I', table_name || '_select', table_name);
    execute format('create policy %I on public.%I for select to authenticated using (organization_id = (select private.current_pos_org_id()))', table_name || '_select', table_name);
    execute format('drop policy if exists %I on public.%I', table_name || '_insert', table_name);
    execute format('create policy %I on public.%I for insert to authenticated with check (organization_id = (select private.current_pos_org_id()))', table_name || '_insert', table_name);
    execute format('drop policy if exists %I on public.%I', table_name || '_update', table_name);
    execute format('create policy %I on public.%I for update to authenticated using (organization_id = (select private.current_pos_org_id())) with check (organization_id = (select private.current_pos_org_id()))', table_name || '_update', table_name);
    execute format('drop policy if exists %I on public.%I', table_name || '_delete', table_name);
    execute format('create policy %I on public.%I for delete to authenticated using (organization_id = (select private.current_pos_org_id()) and (select private.pos_has_role(array[''owner'',''admin'',''manager''])))', table_name || '_delete', table_name);
  end loop;

  foreach table_name in array array[
    'pos_suppliers','pos_purchases','pos_purchase_items','pos_expenses','pos_vouchers','pos_account_entries'
  ] loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('drop policy if exists %I on public.%I', table_name || '_select', table_name);
    execute format('create policy %I on public.%I for select to authenticated using (organization_id = (select private.current_pos_org_id()) and (select private.pos_has_role(array[''owner'',''admin'',''manager'',''accountant''])))', table_name || '_select', table_name);
    execute format('drop policy if exists %I on public.%I', table_name || '_write', table_name);
    execute format('create policy %I on public.%I for all to authenticated using (organization_id = (select private.current_pos_org_id()) and (select private.pos_has_role(array[''owner'',''admin'',''manager'',''accountant'']))) with check (organization_id = (select private.current_pos_org_id()) and (select private.pos_has_role(array[''owner'',''admin'',''manager'',''accountant''])))', table_name || '_write', table_name);
  end loop;

  foreach table_name in array array['pos_employees','pos_attendance','pos_payroll'] loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('drop policy if exists %I on public.%I', table_name || '_select', table_name);
    execute format('create policy %I on public.%I for select to authenticated using (organization_id = (select private.current_pos_org_id()) and (select private.pos_has_role(array[''owner'',''admin'',''manager''])))', table_name || '_select', table_name);
    execute format('drop policy if exists %I on public.%I', table_name || '_write', table_name);
    execute format('create policy %I on public.%I for all to authenticated using (organization_id = (select private.current_pos_org_id()) and (select private.pos_has_role(array[''owner'',''admin'',''manager'']))) with check (organization_id = (select private.current_pos_org_id()) and (select private.pos_has_role(array[''owner'',''admin'',''manager''])))', table_name || '_write', table_name);
  end loop;
end $$;

alter table public.pos_audit_logs enable row level security;
drop policy if exists pos_audit_logs_select on public.pos_audit_logs;
create policy pos_audit_logs_select on public.pos_audit_logs for select to authenticated
using (organization_id = (select private.current_pos_org_id()) and (select private.pos_has_role(array['owner','admin','manager'])));
drop policy if exists pos_audit_logs_insert on public.pos_audit_logs;
create policy pos_audit_logs_insert on public.pos_audit_logs for insert to authenticated
with check (organization_id = (select private.current_pos_org_id()) and user_id = (select auth.uid()));

create or replace function public.pos_bootstrap_owner(company_name text default 'Nerosa Elite')
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  user_id uuid := (select auth.uid());
  org_id bigint;
  user_email text;
begin
  if user_id is null then raise exception 'يجب تسجيل الدخول'; end if;
  select organization_id into org_id from public.pos_profiles where pos_profiles.user_id = user_id;
  if org_id is not null then return org_id; end if;
  select email into user_email from auth.users where id = user_id;
  insert into public.pos_organizations(name) values (coalesce(nullif(trim(company_name), ''), 'Nerosa Elite')) returning id into org_id;
  insert into public.pos_profiles(user_id, organization_id, full_name, email, role)
  values (user_id, org_id, split_part(coalesce(user_email, ''), '@', 1), user_email, 'owner');
  return org_id;
end;
$$;
revoke all on function public.pos_bootstrap_owner(text) from public, anon;
grant execute on function public.pos_bootstrap_owner(text) to authenticated;

create or replace function public.pos_create_sale(
  p_customer_id bigint,
  p_sale_type text,
  p_currency text,
  p_discount numeric,
  p_paid numeric,
  p_items jsonb,
  p_installment_count integer default 0,
  p_first_due date default null,
  p_notes text default null
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  org_id bigint := (select private.current_pos_org_id());
  sale_id bigint;
  invoice_no text;
  subtotal_value numeric(14,3) := 0;
  total_value numeric(14,3);
  paid_value numeric(14,3);
  due_value numeric(14,3);
  item jsonb;
  product_row public.pos_products%rowtype;
  qty numeric(14,3);
  price_value numeric(14,3);
  each_installment numeric(14,3);
  i integer;
begin
  if org_id is null then raise exception 'الحساب غير مربوط بالشركة'; end if;
  if p_sale_type not in ('retail','wholesale','credit','installment') then raise exception 'نوع البيع غير صحيح'; end if;
  if p_currency not in ('IQD','USD') then raise exception 'العملة غير صحيحة'; end if;
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then raise exception 'السلة فارغة'; end if;

  insert into public.pos_sales(organization_id, customer_id, sale_type, currency, discount, paid, notes, created_by)
  values (org_id, p_customer_id, p_sale_type, p_currency, greatest(coalesce(p_discount,0),0), 0, p_notes, (select auth.uid()))
  returning id into sale_id;

  for item in select value from jsonb_array_elements(p_items) loop
    qty := coalesce((item ->> 'quantity')::numeric, 0);
    if qty <= 0 then raise exception 'الكمية غير صحيحة'; end if;
    select * into product_row from public.pos_products
    where id = (item ->> 'product_id')::bigint and organization_id = org_id and is_active = true
    for update;
    if not found then raise exception 'المنتج غير موجود'; end if;
    if product_row.stock < qty then raise exception 'المخزون غير كافٍ للمنتج %', product_row.name; end if;
    price_value := coalesce(nullif(item ->> 'unit_price','')::numeric,
      case when p_sale_type = 'wholesale' then product_row.wholesale_price else product_row.retail_price end);
    if price_value < 0 then raise exception 'السعر غير صحيح'; end if;

    insert into public.pos_sale_items(organization_id, sale_id, product_id, product_name, barcode, quantity, unit_price)
    values (org_id, sale_id, product_row.id, product_row.name, product_row.barcode, qty, price_value);
    update public.pos_products set stock = stock - qty where id = product_row.id;
    insert into public.pos_stock_movements(organization_id, product_id, movement_type, quantity, reference_type, reference_id, created_by)
    values (org_id, product_row.id, 'sale', -qty, 'sale', sale_id, (select auth.uid()));
    subtotal_value := subtotal_value + (qty * price_value);
  end loop;

  total_value := greatest(subtotal_value - greatest(coalesce(p_discount,0),0), 0);
  paid_value := least(greatest(coalesce(p_paid,0),0), total_value);
  due_value := total_value - paid_value;
  if due_value > 0 and p_customer_id is null then raise exception 'اختر العميل للبيع الآجل أو القسط'; end if;
  invoice_no := 'NER-S-' || to_char(current_date, 'YYYYMMDD') || '-' || lpad(sale_id::text, 6, '0');
  update public.pos_sales set invoice_number = invoice_no, subtotal = subtotal_value, total = total_value, paid = paid_value where id = sale_id;

  if p_customer_id is not null then
    insert into public.pos_account_entries(organization_id, party_type, party_id, entry_type, direction, amount, currency, reference_type, reference_id, notes, created_by)
    values (org_id, 'customer', p_customer_id, 'sale', 'debit', total_value, p_currency, 'sale', sale_id, invoice_no, (select auth.uid()));
    if paid_value > 0 then
      insert into public.pos_account_entries(organization_id, party_type, party_id, entry_type, direction, amount, currency, reference_type, reference_id, notes, created_by)
      values (org_id, 'customer', p_customer_id, 'sale_payment', 'credit', paid_value, p_currency, 'sale', sale_id, invoice_no, (select auth.uid()));
    end if;
  end if;

  if p_sale_type = 'installment' and due_value > 0 and p_installment_count > 0 then
    each_installment := round(due_value / p_installment_count, 3);
    for i in 1..p_installment_count loop
      insert into public.pos_installments(organization_id, sale_id, customer_id, installment_number, due_date, amount)
      values (
        org_id, sale_id, p_customer_id, i,
        coalesce(p_first_due, current_date + interval '1 month')::date + ((i - 1) * interval '1 month'),
        case when i = p_installment_count then due_value - (each_installment * (p_installment_count - 1)) else each_installment end
      );
    end loop;
  end if;

  insert into public.pos_audit_logs(organization_id, user_id, action, entity_type, entity_id, details)
  values (org_id, (select auth.uid()), 'create_sale', 'sale', sale_id, jsonb_build_object('invoice', invoice_no, 'total', total_value));
  return jsonb_build_object('id', sale_id, 'invoice_number', invoice_no, 'subtotal', subtotal_value, 'total', total_value, 'paid', paid_value, 'due', due_value);
end;
$$;

create or replace function public.pos_create_purchase(
  p_supplier_id bigint,
  p_supplier_invoice text,
  p_currency text,
  p_discount numeric,
  p_paid numeric,
  p_items jsonb,
  p_notes text default null
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  org_id bigint := (select private.current_pos_org_id());
  purchase_id bigint;
  invoice_no text;
  subtotal_value numeric(14,3) := 0;
  total_value numeric(14,3);
  paid_value numeric(14,3);
  item jsonb;
  product_row public.pos_products%rowtype;
  qty numeric(14,3);
  cost_value numeric(14,3);
begin
  if org_id is null then raise exception 'الحساب غير مربوط بالشركة'; end if;
  if p_currency not in ('IQD','USD') then raise exception 'العملة غير صحيحة'; end if;
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then raise exception 'قائمة المشتريات فارغة'; end if;

  insert into public.pos_purchases(organization_id, supplier_id, supplier_invoice, currency, discount, notes, created_by)
  values (org_id, p_supplier_id, p_supplier_invoice, p_currency, greatest(coalesce(p_discount,0),0), p_notes, (select auth.uid()))
  returning id into purchase_id;

  for item in select value from jsonb_array_elements(p_items) loop
    qty := coalesce((item ->> 'quantity')::numeric, 0);
    cost_value := coalesce((item ->> 'unit_cost')::numeric, 0);
    if qty <= 0 or cost_value < 0 then raise exception 'بيانات المشتريات غير صحيحة'; end if;
    select * into product_row from public.pos_products
    where id = (item ->> 'product_id')::bigint and organization_id = org_id
    for update;
    if not found then raise exception 'المنتج غير موجود'; end if;
    insert into public.pos_purchase_items(organization_id, purchase_id, product_id, product_name, quantity, unit_cost)
    values (org_id, purchase_id, product_row.id, product_row.name, qty, cost_value);
    update public.pos_products set stock = stock + qty, cost = cost_value where id = product_row.id;
    insert into public.pos_stock_movements(organization_id, product_id, movement_type, quantity, reference_type, reference_id, created_by)
    values (org_id, product_row.id, 'purchase', qty, 'purchase', purchase_id, (select auth.uid()));
    subtotal_value := subtotal_value + (qty * cost_value);
  end loop;

  total_value := greatest(subtotal_value - greatest(coalesce(p_discount,0),0), 0);
  paid_value := least(greatest(coalesce(p_paid,0),0), total_value);
  invoice_no := 'NER-P-' || to_char(current_date, 'YYYYMMDD') || '-' || lpad(purchase_id::text, 6, '0');
  update public.pos_purchases set invoice_number = invoice_no, subtotal = subtotal_value, total = total_value, paid = paid_value where id = purchase_id;
  if p_supplier_id is not null then
    insert into public.pos_account_entries(organization_id, party_type, party_id, entry_type, direction, amount, currency, reference_type, reference_id, notes, created_by)
    values (org_id, 'supplier', p_supplier_id, 'purchase', 'credit', total_value, p_currency, 'purchase', purchase_id, invoice_no, (select auth.uid()));
    if paid_value > 0 then
      insert into public.pos_account_entries(organization_id, party_type, party_id, entry_type, direction, amount, currency, reference_type, reference_id, notes, created_by)
      values (org_id, 'supplier', p_supplier_id, 'purchase_payment', 'debit', paid_value, p_currency, 'purchase', purchase_id, invoice_no, (select auth.uid()));
    end if;
  end if;
  insert into public.pos_audit_logs(organization_id, user_id, action, entity_type, entity_id, details)
  values (org_id, (select auth.uid()), 'create_purchase', 'purchase', purchase_id, jsonb_build_object('invoice', invoice_no, 'total', total_value));
  return jsonb_build_object('id', purchase_id, 'invoice_number', invoice_no, 'total', total_value, 'paid', paid_value, 'due', total_value - paid_value);
end;
$$;

create or replace function public.pos_pay_installment(p_installment_id bigint, p_amount numeric, p_notes text default null)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  org_id bigint := (select private.current_pos_org_id());
  row_data public.pos_installments%rowtype;
  applied numeric(14,3);
  voucher_id bigint;
  voucher_no text;
  payment_currency text;
begin
  select * into row_data from public.pos_installments where id = p_installment_id and organization_id = org_id for update;
  if not found then raise exception 'القسط غير موجود'; end if;
  select currency into payment_currency from public.pos_sales where id = row_data.sale_id and organization_id = org_id;
  applied := least(greatest(coalesce(p_amount,0),0), row_data.amount - row_data.paid_amount);
  if applied <= 0 then raise exception 'المبلغ غير صحيح'; end if;
  update public.pos_installments set
    paid_amount = paid_amount + applied,
    paid_at = case when paid_amount + applied >= amount then now() else paid_at end,
    status = case when paid_amount + applied >= amount then 'paid' else 'partial' end,
    notes = coalesce(p_notes, notes)
  where id = row_data.id;
  insert into public.pos_vouchers(organization_id, voucher_type, party_type, party_id, amount, currency, notes, created_by)
  values (org_id, 'receipt', 'customer', row_data.customer_id, applied, coalesce(payment_currency, 'IQD'), coalesce(p_notes, 'تسديد قسط'), (select auth.uid()))
  returning id into voucher_id;
  voucher_no := 'NER-V-' || to_char(current_date, 'YYYYMMDD') || '-' || lpad(voucher_id::text, 6, '0');
  update public.pos_vouchers set voucher_number = voucher_no where id = voucher_id;
  insert into public.pos_account_entries(organization_id, party_type, party_id, entry_type, direction, amount, currency, reference_type, reference_id, notes, created_by)
  values (org_id, 'customer', row_data.customer_id, 'installment_payment', 'credit', applied, coalesce(payment_currency, 'IQD'), 'installment', row_data.id, voucher_no, (select auth.uid()));
  return jsonb_build_object('installment_id', row_data.id, 'amount', applied, 'voucher_number', voucher_no);
end;
$$;

create or replace function public.pos_reset_organization(confirm_text text)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  org_id bigint := (select private.current_pos_org_id());
begin
  if org_id is null or not (select private.pos_has_role(array['owner'])) then raise exception 'المالك فقط يمكنه تصفير النظام'; end if;
  if confirm_text <> 'تصفير' then raise exception 'اكتب كلمة تصفير للتأكيد'; end if;
  delete from public.pos_audit_logs where organization_id = org_id;
  delete from public.pos_account_entries where organization_id = org_id;
  delete from public.pos_vouchers where organization_id = org_id;
  delete from public.pos_expenses where organization_id = org_id;
  delete from public.pos_installments where organization_id = org_id;
  delete from public.pos_stock_movements where organization_id = org_id;
  delete from public.pos_sale_items where organization_id = org_id;
  delete from public.pos_sales where organization_id = org_id;
  delete from public.pos_purchase_items where organization_id = org_id;
  delete from public.pos_purchases where organization_id = org_id;
  delete from public.pos_attendance where organization_id = org_id;
  delete from public.pos_payroll where organization_id = org_id;
  delete from public.pos_employees where organization_id = org_id;
  delete from public.pos_suppliers where organization_id = org_id;
  delete from public.pos_customers where organization_id = org_id;
  delete from public.pos_products where organization_id = org_id;
  insert into public.pos_audit_logs(organization_id, user_id, action, details)
  values (org_id, (select auth.uid()), 'system_reset', jsonb_build_object('at', now()));
  return true;
end;
$$;

revoke all on function public.pos_create_sale(bigint,text,text,numeric,numeric,jsonb,integer,date,text) from public, anon;
revoke all on function public.pos_create_purchase(bigint,text,text,numeric,numeric,jsonb,text) from public, anon;
revoke all on function public.pos_pay_installment(bigint,numeric,text) from public, anon;
revoke all on function public.pos_reset_organization(text) from public, anon;
grant execute on function public.pos_create_sale(bigint,text,text,numeric,numeric,jsonb,integer,date,text) to authenticated;
grant execute on function public.pos_create_purchase(bigint,text,text,numeric,numeric,jsonb,text) to authenticated;
grant execute on function public.pos_pay_installment(bigint,numeric,text) to authenticated;
grant execute on function public.pos_reset_organization(text) to authenticated;

create or replace view public.pos_daily_sales
with (security_invoker = true)
as
select
  organization_id,
  sold_at::date as sale_date,
  count(*) as invoices,
  coalesce(sum(total), 0) as total_sales,
  coalesce(sum(paid), 0) as total_paid,
  coalesce(sum(due), 0) as total_due,
  coalesce(sum(discount), 0) as total_discount
from public.pos_sales
where status = 'completed'
group by organization_id, sold_at::date;

drop view if exists public.pos_customer_balances;
create view public.pos_customer_balances
with (security_invoker = true)
as
select
  c.id as customer_id,
  c.organization_id,
  c.name,
  c.phone,
  c.opening_balance + coalesce(sum(
    (case when a.direction = 'debit' then a.amount else -a.amount end)
    * case
        when a.currency = o.default_currency then 1
        when a.currency = 'USD' then o.exchange_rate
        else 1 / o.exchange_rate
      end
  ), 0) as balance
from public.pos_customers c
join public.pos_organizations o on o.id = c.organization_id
left join public.pos_account_entries a
  on a.organization_id = c.organization_id
  and a.party_type = 'customer'
  and a.party_id = c.id
group by c.id, c.organization_id, c.name, c.phone, c.opening_balance, o.default_currency, o.exchange_rate;

grant usage on schema public to authenticated;
grant select, insert, update, delete on table
  public.pos_organizations,
  public.pos_profiles,
  public.pos_products,
  public.pos_customers,
  public.pos_suppliers,
  public.pos_employees,
  public.pos_attendance,
  public.pos_payroll,
  public.pos_sales,
  public.pos_sale_items,
  public.pos_purchases,
  public.pos_purchase_items,
  public.pos_installments,
  public.pos_stock_movements,
  public.pos_expenses,
  public.pos_vouchers,
  public.pos_account_entries,
  public.pos_audit_logs
to authenticated;
grant select on public.pos_daily_sales, public.pos_customer_balances to authenticated;
grant usage, select on all sequences in schema public to authenticated;

revoke all on table
  public.pos_organizations,
  public.pos_profiles,
  public.pos_products,
  public.pos_customers,
  public.pos_suppliers,
  public.pos_employees,
  public.pos_attendance,
  public.pos_payroll,
  public.pos_sales,
  public.pos_sale_items,
  public.pos_purchases,
  public.pos_purchase_items,
  public.pos_installments,
  public.pos_stock_movements,
  public.pos_expenses,
  public.pos_vouchers,
  public.pos_account_entries,
  public.pos_audit_logs
from anon;
